import type { NextPage } from 'next';

import { Container, Timeline } from './styles';

const Experience: NextPage = () => {
  const experiences = [
    { company: 'ThoughtWorks', role: 'Software Developer Consultant', time: 'Abr 2021 - Present' },
    {
      company: 'Vibbra',
      role: 'Front-End Engineer',
      description: 'Working on the rebuild of internal systems using React, TypeScript and Material UI',
      time: 'Out 2021 - Present',
    },
    {
      company: 'Mesa Mobile Thinking',
      role: 'Full-Stack Enginner',
      description:
        'As a Full Stack Engineer I participated in projects in the areas of retail (Dashboard project), healthcare (Dashboard and public content area). Using tools like AdonisJs, PostgreSQL and SQL Server for backend development, Vue.Js for frontend development, Gitlab for versioning and Heroku for deploy in an agile environment with Scrum as the methodology.',
      time: 'Mar 2021 - Fev 2022',
    },
    {
      company: 'Capyba',
      role: 'Front-End Engineer',
      description:
        "Participated of the rebuild of a Brazil's relevant health project using Angular, TypeScript and Clean Architecture concepts",
      time: 'Nov 2021 - Dez 2021',
    },
    {
      company: 'Kurier',
      role: 'Full-End Engineer',
      description:
        'Analysis, development and maintenance of software systems for legal management where I developed the desktop and web version of Kurier Meridio using Delphi 10, AngularJs, SQL Server and SOAP. There are also database migrations from new customers to Kurier Meridio, creation of report scripts, analysis of scripts generated by support',
      time: 'Ago 2019 - Fev 2020',
    },
    {
      company: 'MV Sistemas',
      role: 'Full-End Engineer',
      description:
        'Analysis, development and maintenance of software that helped hospitalar management. I worked as developer of the international version of SoulMV using proprietary framework based on Spring Boot, GitLab for versioning, Oracle for database and Java programming language',
      time: 'Ago 2018 - Ago 2019',
    },
  ];

  return (
    <Container id="experience">
      <div>
        <div className="title">
          <h2>Experiences</h2>
        </div>

        <Timeline>
          {experiences.map((experience, index) => (
            <div
              key={experience.company}
              className={`timeline-item timeline-item-${index % 2 === 0 ? 'right' : 'left'}`}
            >
              <div className="marker" />
              <div className="timeline-content">
                <h3>{experience.company}</h3>

                <span>
                  {experience.role} ({experience.time})
                </span>
                <p>{experience.description}</p>
              </div>
            </div>
          ))}
        </Timeline>
      </div>
    </Container>
  );
};

export default Experience;
