import type { NextPage } from 'next';

import { Container, Timeline } from './styles';

const Experience: NextPage = () => {
  const experiences = [
    {
      company: 'ThoughtWorks',
      role: 'Software Developer Consultant',
      description:
        'Part of the Thoughtworks team as a consulting developer providing services to partner companies. Currently working at the partner company Globo with Javascript technology in the media player for the Player Web and TV platforms (eg Tizen, WebOS)',
      time: 'Apr 2021 - Present',
    },
    {
      company: 'Vibbra',
      role: 'Front-End Engineer',
      description:
        'Working as a Front-End Developer rebuilding internal systems using React, TypeScript and Material UI',
      time: 'Oct 2021 - Present',
    },
    {
      company: 'Mesa Mobile Thinking',
      role: 'Full-Stack Enginner',
      description:
        'As a Full Stack Engineer I participated in projects in the areas of retail (Dashboard project), healthcare (Dashboard and public content area). Using tools like AdonisJs, PostgreSQL and SQL Server for backend development, Vue.Js for frontend development, Gitlab for versioning and Heroku for deploy in an agile environment with Scrum as the methodology',
      time: 'Mar 2020 - Feb 2022',
    },
    {
      company: 'Capyba',
      role: 'Front-End Engineer',
      description:
        'As a freelance front-end developer, I participated in the reconstruction of a relevant healthcare project in Brazil using Angular, TypeScript and Clean Architecture concepts',
      time: 'Nov 2021 - Dec 2021',
    },
    {
      company: 'Kurier',
      role: 'Full-End Engineer',
      description:
        'Analysis, development and maintenance of software systems for legal management where I developed the desktop and web version of Kurier Meridio using Delphi 10, AngularJs, SQL Server and SOAP. There are also database migrations from new customers to Kurier Meridio, creation of report scripts, analysis of scripts generated by support',
      time: 'Aug 2019 - Feb 2020',
    },
    {
      company: 'MV Sistemas',
      role: 'Full-End Engineer',
      description:
        'Analysis, development and maintenance of software that helped hospitalar management. I worked as developer of the international version of SoulMV using proprietary framework based on Spring Boot, GitLab for versioning, Oracle for database and Java programming language',
      time: 'Aug 2018 - Aug 2019',
    },
  ];

  return (
    <Container id="experience">
      <div>
        <div className="title">
          <h2 className="title-section">Experiences</h2>
        </div>

        <Timeline>
          {experiences.map((experience, index) => (
            <div
              key={experience.company}
              className={`timeline-item timeline-item-${index % 2 === 0 ? 'right' : 'left'}`}
            >
              <div className="marker" />
              <div className="timeline-content">
                <h3>{experience.company}</h3>

                <span>
                  {experience.role} ({experience.time})
                </span>
                <p>{experience.description}</p>
              </div>
            </div>
          ))}
        </Timeline>
      </div>
    </Container>
  );
};

export default Experience;
